Heading:
  default: "GEISLINGEN.digital"
  max: 2500
  description:
    en: "The world is moved by ideas and technology!"
Blurb:
  default: "Wir ergänzen das analoge Geislingen"
  max: 180
  description:
    en: "Enter a short blurb about your community - Max length 180 characters"
Link_sections:
  type: list
  list_type: simple
  default: "Company, Learn new things!|Business, Start a new career!|Shop, Buy cool stuff!|Community, The latest news about the people you care about!|World, Check out what's happening"
  description:
    en: "Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered."
Links:
  type: list
  list_type: simple
  default: "Design, Design process, #, blank, Learn the basics|Design, Blog design, #, blank, What makes for a great blog?|Design, Photoshop tutorials, #, blank, Photoshop for beginners|Design, Design trends, #, blank, Stay on top of the current trends!|Code, Wordpress, #, blank, Wordpress code examples|Code, Tools, #, blank, Tools that will make your life easier!|Code, Tutorials, #, blank, Just starting out? We'll guide you through the basics|Business, Blogging, #, blank, Why not start a blog?|Business, Social media, #, blank, Learn how to leverage Social media and make it work for your business|Business, Make money, #, blank, Everyone likes to be paid!|Business, Marketing, #, blank, No business will survive without customers...Here's how to get'em!|Shop, Vectors, #, blank, buy vectors|Shop, Textures, #, blank, buy textures|Shop, UI kits, #, blank, buy UI kits|Shop, PSDs, #, blank, Ready-made PSD's|Community, Your corner, #, blank, Tell us how you feel!|Community, Questions, #, blank, Feel like answering some questions?|Community, Members, #, blank, Say hi to new members|Community, trending, #, blank, Catch up with the latest trending topics!|World, Politics, #, blank, Stay up to date|World, Education, #, blank, The latest research|World, Automotive, #, blank, We cover the latest models!|World, Sports, #, The latest scores|World, Tech, #, Never miss a new gadget"
  description:
    en: "Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered."
Small_links:
  type: list
  list_type: simple
  default: "Privacy, #, self|Terms of service, #, self| About, #, self"
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
Social_links:
  type: list
  list_type: simple
  default: "Facebook, Join us on Facebook, #, blank,fab-facebook|Twitter, show some love on Twitter, #, blank,fab-twitter| Youtube, Check out our latest videos on Youtube, #, blank,fab-youtube"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
Show_footer_on_login_required_page:
  default: true
  description:
    en: "Check this setting if you want the footer to be displayed on the login-required page (only applies if your site is private)"
svg_icons:
  default: "fab-facebook|fab-twitter|fab-youtube"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "





show_on:
  default: top_menu
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
    - below-site-header

background_image:
  type: string
  default: none
  description: Enter an image url

tile_background_image: false

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out



show_for_members:
  type: bool
  default: true
  description:
    en: 'Display the banner for users logged into the forum'
show_for_anon:
  type: bool
  default: true
  description:
    en: 'Display the banner for anonymous users'
display_on_mobile:
  type: bool
  default: true
  description:
    en: 'Display the banner on mobile devices'
display_on_desktop:
  type: bool
  default: true
  description:
    en: 'Display the banner on desktop computers'
display_on_homepage:
  type: bool
  default: true
  description:
    en: 'Display the banner on the homepage'
url_must_contain:
  type: list
  list_type: simple
  default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
  description:
    en: 'Enter paths that should display the banner. Add <code>*</code> to the end of the path as a wildcard'
dismissible:
  type: bool
  default: false
  description:
    en: 'Allow the banner to be closed by users'
collapsible:
  type: bool
  default: false
  description:
    en: 'Allow the banner to be expanded and collapsed by users'
default_collapsed_state:
  type: enum
  default: collapsed
  choices:
    - expanded
  description:
    en: 'Default collapsed state when collapsible setting is enabled'
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
  description:
    en: 'The lifespan of the cookie used to remember if the banner has been closed, expanded, or collapsed.
         If set to "none", NO cookies will be used with this component, and any previously created cookies
         related to the banner will be deleted the next time a user performs a full page load. The values are
         measured as a single unit, so setting "year" will be one year, "week" will be one week, etc.'
cookie_name:
  type: string
  default: "v1"
  description:
    en: 'When important changes are made to the banner, you must change the cookie name to ensure all your users see the changes.'
full_width_banner:
  type: bool
  default: false
  description:
    en: 'Display the banner at full browser width'
swap_default_positioning:
  type: bool
  default: false
  description:
    en: 'If there is another banner-related component active, use this to swap its position with the Versatile Banner'
banner_background_image:
  type: string
  default: "https://i.imgur.com/k7SnZth.jpg"
  description:
    en: 'The source url for your background image. Tip: You can upload an image to your main theme and use the url from that,
         but make sure that you do not use "Uploads" section of this component. Any uploads added to this component will be
         deleted whenever it is updated.'
background_color:
  type: string
  default: "#EED4A1"
  description:
    en: 'Used in place of a background image'
primary_text_color:
  type: string
  default: "#000"
  description:
    en: 'The main text color of the banner'
secondary_text_color:
  type: string
  default: "#FF6C00"
  description:
    en: 'The text color of the icon and text headings, and the button background color.'
link_text_color:
  type: string
  default: "#0f82af"
  description:
    en: 'The text color links within the banner.
        <br><br><br>
        <h2>Banner Content Customization</h2>
        Customize the content of the banner with HTML. If you need to style your custom content
        with CSS, create a separate theme component. Leave the content blank to exclude a column.
        While a fourth column is provided, it will likely result in too much content for the
        available space. Be sure you are happy with your configuration across different brower widths.'
main_heading_content:
  type: string
  textarea: true
  default: |
    <h2 class="x-title">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    </h2>
    <div class="colored-line"></div>
    <div class="description">
      <p>
        Nulla ullamcorper augue vel sodales pellentesque. Sed
        vitae sapien sit amet mauris consequat malesuada.
        Vestibulum vitae iaculis nisl, vel aliquet velit.
        Fusce venenatis laoreet diam, non dictum nisl
        vestibulum non.
      </p>
    </div>
    <div class="colored-line"></div>
first_column_content:
  type: string
  textarea: true
  default: |
    <h3>A simple box</h3>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Sed id congue eros, sit amet suscipit libero. Nunc vitae
      placerat est.
    </p>
    <div class="banner-list">
      <ul>
        <li><a href="https://twitter.com/discourse" target="_blank">A tweet</a> to wake up my friends</li>
        <li>Put the photos in the bag</li>
        <li>Rearrange books in the study</li>
        <li>And the notes?</li>
      </ul>
    </div>
second_column_content:
  type: string
  textarea: true
  default: |
    <h3>Another simple box</h3>
    <p>
      Integer velit ante,
      <a href="https://discourse.org">DISCOURSE</a>
      amet tristique in, gravida at ligula. Sed gravida mauris id
      neque vestibulum semper. Suspendisse potenti. Nam
      nec maximus ligula. Ut eget semper est. Sed ornare
      sit amet justo eu rutrum. Integer sit amet facilisis ipsum.
    </p>

    <div class="buttons" id="my-button">
      <a href="#" class="btn btn-icon-text">My new button</a>
    </div>
third_column_content:
  type: string
  textarea: true
  default: |
    <h3>Yet another simple box</h3>
    <p>
      Pellentesque ut lacinia nunc, eu molestie nulla.
      Pellentesque viverra nisi urna, at hendrerit nisl
      sodales in. Morbi auctor sodales nisi, eget aliquam
      justo maximus in. Suspendisse a felis a massa
      elementum pellentesque quis eget dolor. Orci varius
      natoque penatibus et magnis dis parturient montes,
      nascetur ridiculus mus.
    </p>
fourth_column_content:
  type: string
  textarea: true
  default: ''
  description:
    en: '<br><br>
        <h2>Column Sizes</h2>
        Use a percentage to make columns more wide or narrow. When set to "auto", the column will fill the
        available space evenly with other "auto" columns.'
first_column_size:
  type: string
  default: 'auto'
second_column_size:
  type: string
  default: 'auto'
third_column_size:
  type: string
  default: 'auto'
fourth_column_size:
  type: string
  default: ''
  description:
    en: '<br><br>
        <h2>Column Icons</h2>
        Use font awesome or a link to an image for the icon at the top of the columns.
        Accepted font awesome formats: <b>fa-icon</b>, <b>far fa-icon</b> or <b>fab fa-icon</b>.
        <a href="https://fontawesome.com/icons?d=gallery&m=free" target="_blank">Click Here</a>
        to view the list of available icons.'
first_column_icon:
  type: string
  default: 'cog'
second_column_icon:
  type: string
  default: 'https://d11a6trkgmumsb.cloudfront.net/original/3X/b/3/b33be9538df3547fcf9d1a51a4637d77392ac6f9.png'
third_column_icon:
  type: string
  default: 'wrench'
fourth_column_icon:
  type: string
  default: ''
